name: Nuclei

on:
  workflow_dispatch:
    inputs:
        Host:
            description: "Host a ser escaneado"
            required: true
            default: "testaspnet.vulnweb.com"
            type: string
        Severity:
            description: "Filtro de severidade"
            required: true
            default: "info,low,medium,high,critical"
            type: string
        Tags:
            description: "Grupo de checks por tags"
            required: false
            default: ""
            # default: "headers"
            type: string
        Rate-limit: 
            description: "Num de request por segundo"
            required: true
            default: '150'
            type: number

  # push:
  #   branches:
  #       - main

jobs:
    scan:
        runs-on: ubuntu-latest
        permissions:
          security-events: write
          contents: read
          actions: read
        steps:
        - uses: actions/checkout@v4

        - name: Install Nuclei
          uses: projectdiscovery/nuclei-action@v3
          with:
            version: latest
            install-only: true

        - name: Verify install
          run: nuclei -version

        - name: Update templates
          run: nuclei -update-templates

        - name: Run scan - ${{ github.event.inputs.Host || 'testaspnet.vulnweb.com' }}
          run: | 
                nuclei -u ${{ github.event.inputs.Host || 'testaspnet.vulnweb.com' }} -json-export ScanResult.json -rate-limit ${{ github.event.inputs.Rate-limit || 10 }} -concurrency 1 -omit-raw -tags '${{ github.event.inputs.Tags || '' }}' --verbose -timestamp -timeout 5 -severity ${{ github.event.inputs.Severity || 'info' }} -se nuclei.sarif

        - name: Upload SARIF results to GitHub Security Tabs
          uses: github/codeql-action/upload-sarif@v4
          if: success() || failure() 
          with:
            sarif_file: nuclei.sarif
            category: nuclei-analysis        

        - name: Upload Results
          uses: actions/upload-artifact@v7
          with:
            path: ScanResult.json
            archive: false 

                